import pickle
import numpy as np
import pandas as pd
import argparse


def list_of_columns(odata, tdata):
    """
    Using OlegDB and TCRD files, make a list of columns that will be used
    for comparison.
    """
    r_cols = set(tdata.columns)
    print(f"Number of columns in R file...{len(r_cols)}")

    p_cols = set(odata.columns)
    print(f"Number of columns in Python file...{len(p_cols)}")

    if len(p_cols) == len(r_cols):
        selected_cols = []
        for col in p_cols:
            if isinstance(col, int):
                if "pp." + str(col) in r_cols:
                    selected_cols.append(col)
            elif col in r_cols:
                selected_cols.append(col)
            else:
                print(f"Unmatched column...{col}")
        print(f"Total common column...{len(selected_cols)}")
    else:
        print("Python and R file do not have the same number of features")
        return 0

    # if selected columns is less than total columns, something is wrong.
    if len(selected_cols) == len(p_cols):
        return selected_cols
    else:
        print("OlegDB and TCRD files have different columns")
        return 0


def check_feature_difference(cols, odata, tdata, dp):
    """
    Find if R and Python files have different features
    """
    matched_cols = set()
    unmatched_cols = set()
    for col in cols:
        if isinstance(col, int):
            r_col_data = set(
                [round(float(v), dp) for v in tdata["pp." + str(col)]]
            )
            p_col_data = set([round(float(v), dp) for v in odata[col]])
        else:
            r_col_data = set([round(float(v), dp) for v in tdata[col]])
            p_col_data = set([round(float(v), dp) for v in odata[col]])

        unmatched = len(r_col_data.difference(p_col_data))
        if unmatched == 0:
            matched_cols.add(col)
        else:
            unmatched_cols.add(col)

    return matched_cols, unmatched_cols


if __name__ == "__main__":
    """
    start of the code
    """
    dp = 2  # decimal places
    parser = argparse.ArgumentParser(
        description="Compare features generated by R and Python"
    )
    parser.add_argument(
        "--olegfile",
        required=True,
        help="Features pickle file generated using OlegDB",
    )
    parser.add_argument(
        "--tcrdfile",
        required=True,
        help="Features pickle file generated using TCRD",
    )
    parser.add_argument(
        "--decimalplace",
        default=dp,
        type=int,
        help="Decimal places of features to select for comparison",
    )
    parser.add_argument(
        "-v", "--verbose", action="count", default=0, help="verbosity"
    )

    args = parser.parse_args()

    # load R and Python data
    olegdata = pickle.load(open(args.olegfile, "rb"))
    tcrddata = pickle.load(open(args.tcrdfile, "rb"))

    # Processing starts here for training set
    selected_cols = list_of_columns(olegdata, tcrddata)
    if selected_cols == 0:
        print("Program failed!!!")
    else:
        matched_cols, unmatched_cols = check_feature_difference(
            selected_cols, olegdata, tcrddata, args.decimalplace
        )
        print(
            "Number of features with the same values in OlegDB and TCRD files...{0}".format(
                len(matched_cols)
            )
        )
        print(
            "Number of features with the different values in OlegDB and TCRD files...{0}".format(
                len(unmatched_cols)
            )
        )
        print("Features with different values in OlegDB and TCRD files:")
        print(unmatched_cols)
